### ISSUE TITLE
希望可以添加rust相关文档

### ISSUE THREAD

**Issue by Sweechirly** [docschina/docschina-issue-discussions-open#14]

**Comment by hello-lizhihua** [comment]
收录了 https://www.rust-lang.org/zh-CN/

**Comment by Sweechirly** [comment]
> 收录了 https://www.rust-lang.org/zh-CN/

https://doc.rust-lang.org/book/
方便加这个吗

**Comment by hello-lizhihua** [comment]
已收录。清下缓存就能看到

**Comment by Sweechirly** [comment]
> 已收录。清下缓存就能看到

您说的是底下的非官方翻译吗

**Comment by hello-lizhihua** [comment]
这个不算文档，在编程教程分类里面。

**Comment by Sweechirly** [comment]
> 这个不算文档，在编程教程分类里面。

啥意思？
