### ISSUE TITLE
flow-STATIC TYPE CHECKER FOR JAVASCRIPT

### ISSUE THREAD

**Issue by XJYDream** [docschina/docschina-issue-discussions-open#16]
读框架源码，提示 类型注释只能在 TypeScript 文件中使用。其实式 .js文件 编译器使用ts解析出错，查询为flow语法  可否增加flow文档

**Comment by hello-lizhihua** [comment]
flow 现在官方不维护了，而且也没有特别完善的中文翻译，所以暂时不会收录
