### ISSUE TITLE
官网链接的mobx教程很旧了，麻烦换成新的

### ISSUE THREAD

**Issue by ghost** [docschina/docschina-issue-discussions-open#23]
https://docschina.org/  链接到了 https://cn.mobx.js.org/   

但这个网址里的 mobx版本已经很旧了，   

建议把指向链接 换成  https://zh.mobx.js.org/README.html

**Comment by QC-L** [comment]
好，我调整下

**Comment by ghost** [comment]
我现在不用mobx了， 用react-query 了
